# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 12:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifr', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0441\u0441\u0438\u0440\u044b',
                'verbose_name_plural': '\u041a\u0430\u0441\u0441\u0438\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('stop', models.DateTimeField()),
            ],
            options={
                'verbose_name': '\u0418\u0433\u0440\u044b',
                'verbose_name_plural': '\u0418\u0433\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Playing_dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifr', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u0418\u0433\u0440\u043e\u0432\u044b\u0435 \u0431\u043b\u044e\u0434\u0430',
                'verbose_name_plural': '\u0418\u0433\u0440\u043e\u0432\u044b\u0435 \u0431\u043b\u044e\u0434\u0430',
            },
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('shifr', models.IntegerField()),
                ('p', models.FloatField()),
                ('middle_check', models.FloatField(default=1.0)),
                ('checks_per_hour', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '\u0420\u0435\u0441\u0442\u043e\u0440\u0430\u043d\u044b',
                'verbose_name_plural': '\u0420\u0435\u0441\u0442\u043e\u0440\u0430\u043d\u044b',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('summa', models.FloatField()),
                ('summa_normal', models.FloatField()),
                ('count_dishers', models.FloatField(blank=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Cashiers')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Games')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Restaurants')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u0434\u0430\u0436\u0438',
                'verbose_name_plural': '\u041f\u0440\u043e\u0434\u0430\u0436\u0438',
            },
        ),
    ]
