# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='start',
            new_name='finish',
        ),
        migrations.RenameField(
            model_name='games',
            old_name='stop',
            new_name='start_game',
        ),
    ]
