# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_restaurants_raiting_restaurants_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants_raiting',
            old_name='raiting',
            new_name='peoples',
        ),
    ]
