# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-02 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20170122_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurants_result',
            options={'verbose_name': '\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442: \u043f\u043e \u0440\u0435\u0441\u0442\u043e\u0440\u0430\u043d\u0443', 'verbose_name_plural': '\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442: \u043f\u043e \u0440\u0435\u0441\u0442\u043e\u0440\u0430\u043d\u0443'},
        ),
    ]
