# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20170202_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playing_dishes',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Games'),
        ),
    ]
