# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20170208_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiers',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
