# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 08:48
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_cashiers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashiers',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
