# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20170217_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiers',
            name='model_pic',
            field=models.ImageField(default=b'pic_folder/no-img.jpg', upload_to=b'pic_folder'),
        ),
    ]
