# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_cashiers_model_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashiers',
            name='id',
        ),
        migrations.AlterField(
            model_name='cashiers',
            name='shifr',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
