# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_auto_20170306_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiers',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashiers',
            name='shifr',
            field=models.IntegerField(),
        ),
    ]
