# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-01 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_sales_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('server', models.IntegerField()),
                ('sifr', models.CharField(max_length=20)),
                ('gaming', models.BooleanField()),
                ('name', models.CharField(blank=True, max_length=200)),
                ('quant', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Games')),
            ],
            options={
                'verbose_name': '\u0427\u0435\u043a\u0438',
                'verbose_name_plural': '\u0427\u0435\u043a\u0438',
            },
        ),
    ]
