# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-01 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='summa',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
