# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-01 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_orders_summa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='summa',
            new_name='paysum',
        ),
    ]
